Retry poll (#12)
* Removed extra sys.exit()s;
_die_on_error() made static;
Minor formatting fixes

* Switched to API v3

* Improved error processing in _handle_api_error()

* Introduced AccessProblem exception to fully replace SystemExit

* Typo fix

* Fixed from_cache requests by adding return_all=done to requests (per API documentation)

* Reverted back to API v2

* Reverted back to API v3

* Unifying of URL parameters order

* Error handling fixed

* errorMessage renamed to error_message

* Minor formatting fix

* _handle_api_error() now returns JSON and prints it for debugging purposes

* Some basic debug logging added

* Exception logging improved

* _trigger_new_assessment() and _poll_api() refactored to allow return of a complete cached result at once if it happens

* Minor fix to logging

* Revert "_handle_api_error() now returns JSON and prints it for debugging purposes"

This reverts commit 859609723723834c53ae460122760cf2f8e4ef9f.

* Fixied response JSON handling after reverting _handle_api_error() to return Response, not JSON

* Fixed what looks like a bug causing AttributeError: 'bool' object has no attribute 'get'
in line 327: LOGGER.debug('Testing {} host(s)'.format(len(_status.get('endpoints'))))
AttributeError: 'bool' object has no attribute 'get'
;
Also remove a couple of seemingly unneeded lines of code

* Fixed exception at JSON parsing error

* Fixed naming conflict

Co-authored-by: Vasily Zakharov <v.zakharov@wwpass.com>